### ISSUE TITLE
Maximum call stack size exceeded

### ISSUE THREAD

**Issue by TinyPandas** [fiatjaf/glua#1]
Hello, 

I've recently incorporated this library into my Discord bot in hopes to allow users to compile Lua straight from discord! I immediately went to overwrite the implemented `print` method so I could grab the output and store it so I could then later return it to the user. 

```
                print: function() {
                    var args = Array.prototype.slice.call(arguments);

                    console.log(`Arg count: ${args.length}`);
                    if (args.length > 1) {
                        console.log('multiple things to print');
                        var line = [];
                        for (arg of args) {
                            line.push('arg');
                        }
                        console.log(line.join(" "));
                        output.push(line.join(" "));
                    } else {
                        console.log('single thing to print');
                        output.push(args[0] || 'nil');
                    }
                },
```

Something like this, it's grown into a mess as of late. However, what I've noticed is that if I run `print(_G)` or anything that is stored as a table, it will render the above error: `Maximum call stack size exceeded`. I'm not sure how to go about handling this issue, and it's rather hard to go based on zero documentation. So any help would be appreciated! Thanks!

**Comment by fiatjaf** [comment]
1. What is your bot? I'm curious about the use case. I also made a bot that runs Lua, but for Telegram, and in Go: https://github.com/fiatjaf/runluabot (using a different set of libraries)
2. I'm not knowledgeable enough to help you with this. Could try debugging, but I'm in a rush now. Have you tried using https://github.com/fiatjaf/flua as recommended in the description of this library? I've used that one much more extensively than this and it worked great.

(Although flua tells you to not install fengari from npm that recommendation is only valid for browsers. If you're doing it in Node.js you should install fengari from npm.)

**Comment by TinyPandas** [comment]
1. my bot is a generic discord bot. Just meant to accept a command in the format of `;lua <src>`. 
2. I haven't looked at flua, as your readme said something about it's integration for web browsers, and that's not what I'm looking for. However I was not aware of it being fine to install and setup strictly from npm for node projects. So I can definitely make the switch.
